version: '3.8'
services:
  # Django app
  backend_email:
    build: .
    image: boomslag/auth:0.0.1
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - DEBUG=False
      - SECRET_KEY=d1wc#rn+chiehol+wz)t+s2ghxd4kq@_2#d#*t^7lee_z4@!e3
      - DATABASE_URL=postgres://boomslag_ms_email_postgres_user:vy6QKrrs44mmEXKg9E9HS3iNpXY9ry6t@dpg-cgon5ggu9tun42psgqag-a.oregon-postgres.render.com/boomslag_ms_email_postgres
      - REDIS_URL=rediss://red-cgon52d269v5rjchi4tg:WhMhCLBKkkrmX8bvjy64x39o0Dct3i2j@oregon-redis.render.com:6379
      - REDIS_PASSWORD=WhMhCLBKkkrmX8bvjy64x39o0Dct3i2j

  # Event Queue Kafka
  queue_email:
    build: .
    image: boomslag/auth:0.0.1
    command: >
      sh -c "python consumer.py"